# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.state_a07_enum import StateA07Enum

class TestStateA07Enum(unittest.TestCase):
    """StateA07Enum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateA07Enum(self):
        """Test StateA07Enum"""
        # inst = StateA07Enum()

if __name__ == '__main__':
    unittest.main()
