# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.v1_public_signals_geography_retrieve200_response import V1PublicSignalsGeographyRetrieve200Response

class TestV1PublicSignalsGeographyRetrieve200Response(unittest.TestCase):
    """V1PublicSignalsGeographyRetrieve200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PublicSignalsGeographyRetrieve200Response:
        """Test V1PublicSignalsGeographyRetrieve200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PublicSignalsGeographyRetrieve200Response`
        """
        model = V1PublicSignalsGeographyRetrieve200Response()
        if include_optional:
            return V1PublicSignalsGeographyRetrieve200Response(
                type = 'FeatureCollection',
                features = [
                    signals_api_client.models.v1_public_signals_geography_retrieve_200_response_features_inner.v1_public_signals_geography_retrieve_200_response_features_inner(
                        type = 'Feature', 
                        geometry = signals_api_client.models.v1_private_signals_context_near_geography_retrieve_200_response_features_inner_geometry.v1_private_signals_context_near_geography_retrieve_200_response_features_inner_geometry(
                            type = 'Point', 
                            coordinates = [4.890659,52.373069], ), 
                        properties = signals_api_client.models.v1_public_signals_geography_retrieve_200_response_features_inner_properties.v1_public_signals_geography_retrieve_200_response_features_inner_properties(
                            category = signals_api_client.models.v1_public_signals_geography_retrieve_200_response_features_inner_properties_category.v1_public_signals_geography_retrieve_200_response_features_inner_properties_category(
                                name = 'Overig', 
                                slug = 'overig', 
                                parent = signals_api_client.models.v1_public_signals_geography_retrieve_200_response_features_inner_properties_category_parent.v1_public_signals_geography_retrieve_200_response_features_inner_properties_category_parent(
                                    name = 'Overig', 
                                    slug = 'overig', ), ), 
                            created_at = '2023-06-01T00:00Z', ), )
                    ]
            )
        else:
            return V1PublicSignalsGeographyRetrieve200Response(
        )
        """

    def testV1PublicSignalsGeographyRetrieve200Response(self):
        """Test V1PublicSignalsGeographyRetrieve200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
