# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.links6_sia_children_inner import Links6SiaChildrenInner

class TestLinks6SiaChildrenInner(unittest.TestCase):
    """Links6SiaChildrenInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Links6SiaChildrenInner:
        """Test Links6SiaChildrenInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Links6SiaChildrenInner`
        """
        model = Links6SiaChildrenInner()
        if include_optional:
            return Links6SiaChildrenInner(
                href = 'https://api.example.com/signals/v1/private/signals/3'
            )
        else:
            return Links6SiaChildrenInner(
        )
        """

    def testLinks6SiaChildrenInner(self):
        """Test Links6SiaChildrenInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
