# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.v1_private_signals_context_near_geography_retrieve200_response import V1PrivateSignalsContextNearGeographyRetrieve200Response

class TestV1PrivateSignalsContextNearGeographyRetrieve200Response(unittest.TestCase):
    """V1PrivateSignalsContextNearGeographyRetrieve200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PrivateSignalsContextNearGeographyRetrieve200Response:
        """Test V1PrivateSignalsContextNearGeographyRetrieve200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PrivateSignalsContextNearGeographyRetrieve200Response`
        """
        model = V1PrivateSignalsContextNearGeographyRetrieve200Response()
        if include_optional:
            return V1PrivateSignalsContextNearGeographyRetrieve200Response(
                type = 'FeatureCollection',
                features = [
                    signals_api_client.models.v1_private_signals_context_near_geography_retrieve_200_response_features_inner.v1_private_signals_context_near_geography_retrieve_200_response_features_inner(
                        type = 'Feature', 
                        geometry = signals_api_client.models.v1_private_signals_context_near_geography_retrieve_200_response_features_inner_geometry.v1_private_signals_context_near_geography_retrieve_200_response_features_inner_geometry(
                            type = 'Point', 
                            coordinates = [4.890659,52.373069], ), 
                        properties = signals_api_client.models.v1_private_signals_context_near_geography_retrieve_200_response_features_inner_properties.v1_private_signals_context_near_geography_retrieve_200_response_features_inner_properties(
                            state = 'm', 
                            state_display = 'Gemeld', ), )
                    ]
            )
        else:
            return V1PrivateSignalsContextNearGeographyRetrieve200Response(
        )
        """

    def testV1PrivateSignalsContextNearGeographyRetrieve200Response(self):
        """Test V1PrivateSignalsContextNearGeographyRetrieve200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
