# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.priority_enum import PriorityEnum

class TestPriorityEnum(unittest.TestCase):
    """PriorityEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriorityEnum(self):
        """Test PriorityEnum"""
        # inst = PriorityEnum()

if __name__ == '__main__':
    unittest.main()
