# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.links1 import Links1

class TestLinks1(unittest.TestCase):
    """Links1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Links1:
        """Test Links1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Links1`
        """
        model = Links1()
        if include_optional:
            return Links1(
                curies = signals_api_client.models._links_1_curies._links_1_curies(
                    href = 'https://api.example.com/signals/relations/', ),
                var_self = signals_api_client.models._links_1_self._links_1_self(
                    href = 'https://api.example.com/signals/v1/private/categories/1', ),
                archives = signals_api_client.models._links_1_archives._links_1_archives(
                    href = 'https://api.example.com/signals/v1/private/signals/1/history/', ),
                sia_questionnaire = signals_api_client.models._links_1_sia_questionnaire._links_1_sia_questionnaire(
                    href = 'https://api.example.com/signals/v1/public/qa/questionnaires/636aacb1-2813-423e-adbe-7ef84d4afc37', ),
                sia_icon = signals_api_client.models._links_1_sia_icon._links_1_sia_icon(
                    href = 'https://api.example.com/media/icons/1.png', )
            )
        else:
            return Links1(
        )
        """

    def testLinks1(self):
        """Test Links1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
