# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.private_signal_serializer_detail import PrivateSignalSerializerDetail

class TestPrivateSignalSerializerDetail(unittest.TestCase):
    """PrivateSignalSerializerDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateSignalSerializerDetail:
        """Test PrivateSignalSerializerDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateSignalSerializerDetail`
        """
        model = PrivateSignalSerializerDetail()
        if include_optional:
            return PrivateSignalSerializerDetail(
                links = signals_api_client.models._links. links(
                    curies = signals_api_client.models._links_1_curies._links_1_curies(
                        href = 'https://api.example.com/signals/relations/', ), 
                    self = signals_api_client.models._links_6_self._links_6_self(
                        href = 'https://api.example.com/signals/v1/private/signals/2', ), 
                    archives = signals_api_client.models._links_6_archives._links_6_archives(
                        href = 'https://api.example.com/signals/v1/private/signals/2/history/', ), 
                    sia:attachments = signals_api_client.models._links_6_sia_attachments._links_6_sia_attachments(
                        href = 'https://api.example.com/signals/v1/private/signals/2/attachments/', ), 
                    sia:pdf = signals_api_client.models._links_6_sia_pdf._links_6_sia_pdf(
                        href = 'https://api.example.com/signals/v1/private/signals/2/pdf/', ), 
                    sia:context = signals_api_client.models._links_6_sia_context._links_6_sia_context(
                        href = 'https://api.example.com/signals/v1/private/signals/2/context/', ), 
                    sia:parent = signals_api_client.models._links_self._links_self(
                        href = 'https://api.example.com/signals/v1/private/signals/1', ), 
                    sia:children = [
                        signals_api_client.models._links_6_sia_children_inner._links_6_sia_children_inner(
                            href = 'https://api.example.com/signals/v1/private/signals/3', )
                        ], ),
                display = '',
                category = signals_api_client.models._nested_category_model._NestedCategoryModel(
                    sub_category = 'https://api.example.com/signals/v1/public/terms/categories/1/sub_categories/2/', 
                    sub = '', 
                    sub_slug = '', 
                    main = '', 
                    main_slug = '', 
                    category_url = 'https://api.example.com/signals/v1/public/terms/categories/1/sub_categories/2/', 
                    departments = '', 
                    created_by = '', 
                    text = '', 
                    deadline = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deadline_factor_3 = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                id = 56,
                id_display = '',
                has_attachments = '',
                location = signals_api_client.models._nested_location_model._NestedLocationModel(
                    id = 56, 
                    stadsdeel = 'A', 
                    buurt_code = '', 
                    area_type_code = '', 
                    area_code = '', 
                    area_name = '', 
                    address = null, 
                    address_text = '', 
                    postcode = '', 
                    geometrie = signals_api_client.models._nested_location_model_geometrie._NestedLocationModel_geometrie(
                        type = 'Point', 
                        coordinates = [12.9721,77.5933], ), 
                    extra_properties = null, 
                    created_by = '', 
                    bag_validated = True, ),
                status = signals_api_client.models._nested_status_model._NestedStatusModel(
                    text = '', 
                    user = '', 
                    state = null, 
                    state_display = '', 
                    target_api = null, 
                    extra_properties = null, 
                    send_email = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email_override = '', ),
                reporter = signals_api_client.models._nested_reporter_model._NestedReporterModel(
                    email = '', 
                    phone = '', 
                    sharing_allowed = True, 
                    allows_contact = True, ),
                priority = signals_api_client.models._nested_priority_model._NestedPriorityModel(
                    priority = 'low', 
                    created_by = '', ),
                notes = [
                    signals_api_client.models._nested_note_model._NestedNoteModel(
                        text = '', 
                        created_by = '', )
                    ],
                type = signals_api_client.models._nested_type_model._NestedTypeModel(
                    code = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = '', ),
                source = '',
                text = '',
                text_extra = '',
                extra_properties = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                incident_date_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                incident_date_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                directing_departments = [
                    signals_api_client.models._nested_department_model._NestedDepartmentModel(
                        id = 56, 
                        code = '', 
                        name = '', 
                        is_intern = True, )
                    ],
                routing_departments = [
                    signals_api_client.models._nested_department_model._NestedDepartmentModel(
                        id = 56, 
                        code = '', 
                        name = '', 
                        is_intern = True, )
                    ],
                attachments = [
                    'https://api.example.com/signals/v1/private/signals/1/attachments/1'
                    ],
                assigned_user_email = ''
            )
        else:
            return PrivateSignalSerializerDetail(
                links = signals_api_client.models._links. links(
                    curies = signals_api_client.models._links_1_curies._links_1_curies(
                        href = 'https://api.example.com/signals/relations/', ), 
                    self = signals_api_client.models._links_6_self._links_6_self(
                        href = 'https://api.example.com/signals/v1/private/signals/2', ), 
                    archives = signals_api_client.models._links_6_archives._links_6_archives(
                        href = 'https://api.example.com/signals/v1/private/signals/2/history/', ), 
                    sia:attachments = signals_api_client.models._links_6_sia_attachments._links_6_sia_attachments(
                        href = 'https://api.example.com/signals/v1/private/signals/2/attachments/', ), 
                    sia:pdf = signals_api_client.models._links_6_sia_pdf._links_6_sia_pdf(
                        href = 'https://api.example.com/signals/v1/private/signals/2/pdf/', ), 
                    sia:context = signals_api_client.models._links_6_sia_context._links_6_sia_context(
                        href = 'https://api.example.com/signals/v1/private/signals/2/context/', ), 
                    sia:parent = signals_api_client.models._links_self._links_self(
                        href = 'https://api.example.com/signals/v1/private/signals/1', ), 
                    sia:children = [
                        signals_api_client.models._links_6_sia_children_inner._links_6_sia_children_inner(
                            href = 'https://api.example.com/signals/v1/private/signals/3', )
                        ], ),
                display = '',
                id = 56,
                id_display = '',
                has_attachments = '',
                text = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                incident_date_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                attachments = [
                    'https://api.example.com/signals/v1/private/signals/1/attachments/1'
                    ],
        )
        """

    def testPrivateSignalSerializerDetail(self):
        """Test PrivateSignalSerializerDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
