# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.state_status_message_template_state_enum import StateStatusMessageTemplateStateEnum

class TestStateStatusMessageTemplateStateEnum(unittest.TestCase):
    """StateStatusMessageTemplateStateEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateStatusMessageTemplateStateEnum(self):
        """Test StateStatusMessageTemplateStateEnum"""
        # inst = StateStatusMessageTemplateStateEnum()

if __name__ == '__main__':
    unittest.main()
