# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.private_user_history_hal import PrivateUserHistoryHal

class TestPrivateUserHistoryHal(unittest.TestCase):
    """PrivateUserHistoryHal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateUserHistoryHal:
        """Test PrivateUserHistoryHal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateUserHistoryHal`
        """
        model = PrivateUserHistoryHal()
        if include_optional:
            return PrivateUserHistoryHal(
                identifier = '',
                when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                what = '',
                action = '',
                description = '',
                who = '',
                user = 56
            )
        else:
            return PrivateUserHistoryHal(
                identifier = '',
                when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                what = '',
                action = '',
                description = '',
                who = '',
                user = 56,
        )
        """

    def testPrivateUserHistoryHal(self):
        """Test PrivateUserHistoryHal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
