# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signals_api_client.models.v1_private_signals_geography_retrieve200_response_features_inner_properties import V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties

class TestV1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties(unittest.TestCase):
    """V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties:
        """Test V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties`
        """
        model = V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties()
        if include_optional:
            return V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties(
                id = 1,
                created_at = '2023-06-01T00:00Z'
            )
        else:
            return V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties(
        )
        """

    def testV1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties(self):
        """Test V1PrivateSignalsGeographyRetrieve200ResponseFeaturesInnerProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
