services:
  openapi-generator-cli:
    image: openapitools/openapi-generator-cli:v7.12.0
    command:
      - "generate"
      - "-i"
      - "https://api.acc.meldingen.amsterdam.nl/signals/schema/"
      - "-g"
      - "python"
      - "-o"
      - "/local"
      - "--package-name"
      - "signals_api_client"
      - "--git-host"
      - "github.com"
      - "--git-user-id"
      - "Amsterdam"
      - "--git-repo-id"
      - "signals-api-client"
      - "--library"
      - "asyncio"
      - "-t"
      - "/local/python"
    volumes:
      - ".:/local"
  signals-api-client:
    image: amsterdam/signals-api-client
    build:
      context: .
    volumes:
      - ".:/opt/signals-api-client"
