# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from signals_api_client.models.links1_curies import Links1Curies
from signals_api_client.models.links6_archives import Links6Archives
from signals_api_client.models.links6_self import Links6Self
from signals_api_client.models.links6_sia_attachments import Links6SiaAttachments
from signals_api_client.models.links6_sia_children_inner import Links6SiaChildrenInner
from signals_api_client.models.links6_sia_context import Links6SiaContext
from signals_api_client.models.links6_sia_pdf import Links6SiaPdf
from signals_api_client.models.links_self import LinksSelf
from typing import Optional, Set
from typing_extensions import Self

class Links6(BaseModel):
    """
    Links6
    """ # noqa: E501
    curies: Optional[Links1Curies] = None
    var_self: Optional[Links6Self] = Field(default=None, alias="self")
    archives: Optional[Links6Archives] = None
    sia_attachments: Optional[Links6SiaAttachments] = Field(default=None, alias="sia:attachments")
    sia_pdf: Optional[Links6SiaPdf] = Field(default=None, alias="sia:pdf")
    sia_context: Optional[Links6SiaContext] = Field(default=None, alias="sia:context")
    sia_parent: Optional[LinksSelf] = Field(default=None, alias="sia:parent")
    sia_children: Optional[Annotated[List[Links6SiaChildrenInner], Field(min_length=0)]] = Field(default=None, alias="sia:children")
    __properties: ClassVar[List[str]] = ["curies", "self", "archives", "sia:attachments", "sia:pdf", "sia:context", "sia:parent", "sia:children"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Links6 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of curies
        if self.curies:
            _dict['curies'] = self.curies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_self
        if self.var_self:
            _dict['self'] = self.var_self.to_dict()
        # override the default output from pydantic by calling `to_dict()` of archives
        if self.archives:
            _dict['archives'] = self.archives.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sia_attachments
        if self.sia_attachments:
            _dict['sia:attachments'] = self.sia_attachments.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sia_pdf
        if self.sia_pdf:
            _dict['sia:pdf'] = self.sia_pdf.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sia_context
        if self.sia_context:
            _dict['sia:context'] = self.sia_context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sia_parent
        if self.sia_parent:
            _dict['sia:parent'] = self.sia_parent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sia_children (list)
        _items = []
        if self.sia_children:
            for _item_sia_children in self.sia_children:
                if _item_sia_children:
                    _items.append(_item_sia_children.to_dict())
            _dict['sia:children'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Links6 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "curies": Links1Curies.from_dict(obj["curies"]) if obj.get("curies") is not None else None,
            "self": Links6Self.from_dict(obj["self"]) if obj.get("self") is not None else None,
            "archives": Links6Archives.from_dict(obj["archives"]) if obj.get("archives") is not None else None,
            "sia:attachments": Links6SiaAttachments.from_dict(obj["sia:attachments"]) if obj.get("sia:attachments") is not None else None,
            "sia:pdf": Links6SiaPdf.from_dict(obj["sia:pdf"]) if obj.get("sia:pdf") is not None else None,
            "sia:context": Links6SiaContext.from_dict(obj["sia:context"]) if obj.get("sia:context") is not None else None,
            "sia:parent": LinksSelf.from_dict(obj["sia:parent"]) if obj.get("sia:parent") is not None else None,
            "sia:children": [Links6SiaChildrenInner.from_dict(_item) for _item in obj["sia:children"]] if obj.get("sia:children") is not None else None
        })
        return _obj


