# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from signals_api_client.models.links1_archives import Links1Archives
from signals_api_client.models.links1_curies import Links1Curies
from signals_api_client.models.links1_self import Links1Self
from signals_api_client.models.links1_sia_icon import Links1SiaIcon
from signals_api_client.models.links1_sia_questionnaire import Links1SiaQuestionnaire
from typing import Optional, Set
from typing_extensions import Self

class Links1(BaseModel):
    """
    Links1
    """ # noqa: E501
    curies: Optional[Links1Curies] = None
    var_self: Optional[Links1Self] = Field(default=None, alias="self")
    archives: Optional[Links1Archives] = None
    sia_questionnaire: Optional[Links1SiaQuestionnaire] = Field(default=None, alias="sia:questionnaire")
    sia_icon: Optional[Links1SiaIcon] = Field(default=None, alias="sia:icon")
    __properties: ClassVar[List[str]] = ["curies", "self", "archives", "sia:questionnaire", "sia:icon"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Links1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of curies
        if self.curies:
            _dict['curies'] = self.curies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_self
        if self.var_self:
            _dict['self'] = self.var_self.to_dict()
        # override the default output from pydantic by calling `to_dict()` of archives
        if self.archives:
            _dict['archives'] = self.archives.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sia_questionnaire
        if self.sia_questionnaire:
            _dict['sia:questionnaire'] = self.sia_questionnaire.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sia_icon
        if self.sia_icon:
            _dict['sia:icon'] = self.sia_icon.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Links1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "curies": Links1Curies.from_dict(obj["curies"]) if obj.get("curies") is not None else None,
            "self": Links1Self.from_dict(obj["self"]) if obj.get("self") is not None else None,
            "archives": Links1Archives.from_dict(obj["archives"]) if obj.get("archives") is not None else None,
            "sia:questionnaire": Links1SiaQuestionnaire.from_dict(obj["sia:questionnaire"]) if obj.get("sia:questionnaire") is not None else None,
            "sia:icon": Links1SiaIcon.from_dict(obj["sia:icon"]) if obj.get("sia:icon") is not None else None
        })
        return _obj


