# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from signals_api_client.models.nested_status_model_state import NestedStatusModelState
from signals_api_client.models.nested_status_model_target_api import NestedStatusModelTargetApi
from typing import Optional, Set
from typing_extensions import Self

class NestedStatusModel(BaseModel):
    """
    NestedStatusModel
    """ # noqa: E501
    text: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = None
    user: Optional[StrictStr]
    state: Optional[NestedStatusModelState] = None
    state_display: StrictStr
    target_api: Optional[NestedStatusModelTargetApi] = None
    extra_properties: Optional[Any] = None
    send_email: Optional[StrictBool] = None
    created_at: datetime
    email_override: Optional[Annotated[str, Field(strict=True, max_length=254)]] = None
    __properties: ClassVar[List[str]] = ["text", "user", "state", "state_display", "target_api", "extra_properties", "send_email", "created_at", "email_override"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NestedStatusModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "user",
            "state_display",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict['state'] = self.state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target_api
        if self.target_api:
            _dict['target_api'] = self.target_api.to_dict()
        # set to None if text (nullable) is None
        # and model_fields_set contains the field
        if self.text is None and "text" in self.model_fields_set:
            _dict['text'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if target_api (nullable) is None
        # and model_fields_set contains the field
        if self.target_api is None and "target_api" in self.model_fields_set:
            _dict['target_api'] = None

        # set to None if extra_properties (nullable) is None
        # and model_fields_set contains the field
        if self.extra_properties is None and "extra_properties" in self.model_fields_set:
            _dict['extra_properties'] = None

        # set to None if email_override (nullable) is None
        # and model_fields_set contains the field
        if self.email_override is None and "email_override" in self.model_fields_set:
            _dict['email_override'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NestedStatusModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "user": obj.get("user"),
            "state": NestedStatusModelState.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "state_display": obj.get("state_display"),
            "target_api": NestedStatusModelTargetApi.from_dict(obj["target_api"]) if obj.get("target_api") is not None else None,
            "extra_properties": obj.get("extra_properties"),
            "send_email": obj.get("send_email"),
            "created_at": obj.get("created_at"),
            "email_override": obj.get("email_override")
        })
        return _obj


