# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from signals_api_client.models.links import Links
from signals_api_client.models.nested_category_model import NestedCategoryModel
from signals_api_client.models.nested_department_model import NestedDepartmentModel
from signals_api_client.models.nested_location_model import NestedLocationModel
from signals_api_client.models.nested_note_model import NestedNoteModel
from signals_api_client.models.nested_priority_model import NestedPriorityModel
from signals_api_client.models.nested_reporter_model import NestedReporterModel
from signals_api_client.models.nested_status_model import NestedStatusModel
from signals_api_client.models.nested_type_model import NestedTypeModel
from typing import Optional, Set
from typing_extensions import Self

class PrivateSignalSerializerList(BaseModel):
    """
    This serializer is used for the list endpoint and when creating a new instance
    """ # noqa: E501
    links: Links = Field(alias="_links")
    display: StrictStr = Field(alias="_display")
    id: StrictInt
    id_display: StrictStr
    signal_id: StrictStr
    source: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    text: Annotated[str, Field(strict=True, max_length=3000)]
    text_extra: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = None
    status: Optional[NestedStatusModel] = None
    location: NestedLocationModel
    category: NestedCategoryModel
    reporter: NestedReporterModel
    priority: Optional[NestedPriorityModel] = None
    type: Optional[NestedTypeModel] = None
    created_at: datetime
    updated_at: datetime
    incident_date_start: datetime
    incident_date_end: Optional[datetime] = None
    operational_date: Optional[datetime] = None
    has_attachments: StrictStr
    extra_properties: Optional[Any] = None
    notes: Optional[List[NestedNoteModel]] = None
    directing_departments: Optional[List[NestedDepartmentModel]] = None
    routing_departments: Optional[List[NestedDepartmentModel]] = None
    attachments: Optional[List[StrictStr]] = None
    parent: Optional[StrictInt] = None
    has_parent: StrictStr
    has_children: StrictStr
    assigned_user_email: Optional[StrictStr] = None
    session: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["_links", "_display", "id", "id_display", "signal_id", "source", "text", "text_extra", "status", "location", "category", "reporter", "priority", "type", "created_at", "updated_at", "incident_date_start", "incident_date_end", "operational_date", "has_attachments", "extra_properties", "notes", "directing_departments", "routing_departments", "attachments", "parent", "has_parent", "has_children", "assigned_user_email", "session"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrivateSignalSerializerList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "display",
            "id",
            "id_display",
            "signal_id",
            "created_at",
            "updated_at",
            "has_attachments",
            "has_parent",
            "has_children",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict['category'] = self.category.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reporter
        if self.reporter:
            _dict['reporter'] = self.reporter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of priority
        if self.priority:
            _dict['priority'] = self.priority.to_dict()
        # override the default output from pydantic by calling `to_dict()` of type
        if self.type:
            _dict['type'] = self.type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item_notes in self.notes:
                if _item_notes:
                    _items.append(_item_notes.to_dict())
            _dict['notes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in directing_departments (list)
        _items = []
        if self.directing_departments:
            for _item_directing_departments in self.directing_departments:
                if _item_directing_departments:
                    _items.append(_item_directing_departments.to_dict())
            _dict['directing_departments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in routing_departments (list)
        _items = []
        if self.routing_departments:
            for _item_routing_departments in self.routing_departments:
                if _item_routing_departments:
                    _items.append(_item_routing_departments.to_dict())
            _dict['routing_departments'] = _items
        # set to None if incident_date_end (nullable) is None
        # and model_fields_set contains the field
        if self.incident_date_end is None and "incident_date_end" in self.model_fields_set:
            _dict['incident_date_end'] = None

        # set to None if operational_date (nullable) is None
        # and model_fields_set contains the field
        if self.operational_date is None and "operational_date" in self.model_fields_set:
            _dict['operational_date'] = None

        # set to None if extra_properties (nullable) is None
        # and model_fields_set contains the field
        if self.extra_properties is None and "extra_properties" in self.model_fields_set:
            _dict['extra_properties'] = None

        # set to None if routing_departments (nullable) is None
        # and model_fields_set contains the field
        if self.routing_departments is None and "routing_departments" in self.model_fields_set:
            _dict['routing_departments'] = None

        # set to None if assigned_user_email (nullable) is None
        # and model_fields_set contains the field
        if self.assigned_user_email is None and "assigned_user_email" in self.model_fields_set:
            _dict['assigned_user_email'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrivateSignalSerializerList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_links": Links.from_dict(obj["_links"]) if obj.get("_links") is not None else None,
            "_display": obj.get("_display"),
            "id": obj.get("id"),
            "id_display": obj.get("id_display"),
            "signal_id": obj.get("signal_id"),
            "source": obj.get("source"),
            "text": obj.get("text"),
            "text_extra": obj.get("text_extra"),
            "status": NestedStatusModel.from_dict(obj["status"]) if obj.get("status") is not None else None,
            "location": NestedLocationModel.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "category": NestedCategoryModel.from_dict(obj["category"]) if obj.get("category") is not None else None,
            "reporter": NestedReporterModel.from_dict(obj["reporter"]) if obj.get("reporter") is not None else None,
            "priority": NestedPriorityModel.from_dict(obj["priority"]) if obj.get("priority") is not None else None,
            "type": NestedTypeModel.from_dict(obj["type"]) if obj.get("type") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "incident_date_start": obj.get("incident_date_start"),
            "incident_date_end": obj.get("incident_date_end"),
            "operational_date": obj.get("operational_date"),
            "has_attachments": obj.get("has_attachments"),
            "extra_properties": obj.get("extra_properties"),
            "notes": [NestedNoteModel.from_dict(_item) for _item in obj["notes"]] if obj.get("notes") is not None else None,
            "directing_departments": [NestedDepartmentModel.from_dict(_item) for _item in obj["directing_departments"]] if obj.get("directing_departments") is not None else None,
            "routing_departments": [NestedDepartmentModel.from_dict(_item) for _item in obj["routing_departments"]] if obj.get("routing_departments") is not None else None,
            "attachments": obj.get("attachments"),
            "parent": obj.get("parent"),
            "has_parent": obj.get("has_parent"),
            "has_children": obj.get("has_children"),
            "assigned_user_email": obj.get("assigned_user_email"),
            "session": obj.get("session")
        })
        return _obj


