# coding: utf-8

"""
    Signalen API

    One of the tasks of a municipality is to maintain public spaces. When citizens have complaints about public spaces they can leave these complaints with the municipality. Signalen (SIG) receives these complaints and is used to track progress towards their resolution. SIG provides an API that is used both by the SIG frontend and external systems that integrate with SIG.

    The version of the OpenAPI document: 2.41.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from signals_api_client.models.v1_public_signals_geography_retrieve200_response_features_inner_properties_category import V1PublicSignalsGeographyRetrieve200ResponseFeaturesInnerPropertiesCategory
from typing import Optional, Set
from typing_extensions import Self

class V1PublicSignalsGeographyRetrieve200ResponseFeaturesInnerProperties(BaseModel):
    """
    V1PublicSignalsGeographyRetrieve200ResponseFeaturesInnerProperties
    """ # noqa: E501
    category: Optional[V1PublicSignalsGeographyRetrieve200ResponseFeaturesInnerPropertiesCategory] = None
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["category", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1PublicSignalsGeographyRetrieve200ResponseFeaturesInnerProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict['category'] = self.category.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1PublicSignalsGeographyRetrieve200ResponseFeaturesInnerProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "category": V1PublicSignalsGeographyRetrieve200ResponseFeaturesInnerPropertiesCategory.from_dict(obj["category"]) if obj.get("category") is not None else None,
            "created_at": obj.get("created_at")
        })
        return _obj


